# Generated by Django 4.1.7 on 2023-05-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalclip',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='historicalclip',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Clip',
        ),
        migrations.DeleteModel(
            name='HistoricalClip',
        ),
    ]
