# Generated by Django 4.1.7 on 2023-05-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0004_alter_camera_file_alter_historicalcamera_file'),
        ('clips', '0002_remove_historicalclip_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='cameras.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('path', models.CharField(max_length=200, verbose_name='ruta')),
                ('file', models.FileField(upload_to='media/%Y-%m-%d')),
                ('size', models.IntegerField(verbose_name='peso')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera', verbose_name='Cámara')),
            ],
            options={
                'verbose_name': 'Clip',
                'verbose_name_plural': 'Clips',
            },
        ),
    ]
