# Generated by Django 4.1.7 on 2023-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_delete_clipactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='file',
            field=models.FileField(upload_to='%Y-%m-%d/'),
        ),
    ]
