# Generated by Django 4.1.7 on 2023-06-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_action_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
