# Generated by Django 4.2.2 on 2023-08-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_facecapture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecapture',
            name='capture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='dataset/', verbose_name='Face Capture'),
        ),
    ]
