# Generated by Django 4.1.7 on 2023-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='port',
            field=models.IntegerField(default=443, verbose_name='Puerto'),
        ),
        migrations.AddField(
            model_name='historicalcamera',
            name='port',
            field=models.IntegerField(default=443, verbose_name='Puerto'),
        ),
    ]
