# Generated by Django 4.1.7 on 2023-03-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_port_historicalcamera_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contrasena Camara'),
        ),
        migrations.AddField(
            model_name='camera',
            name='cam_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario Camara'),
        ),
        migrations.AddField(
            model_name='camera',
            name='file',
            field=models.CharField(default='/camera', max_length=200, verbose_name='Extensión'),
        ),
        migrations.AddField(
            model_name='historicalcamera',
            name='cam_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contrasena Camara'),
        ),
        migrations.AddField(
            model_name='historicalcamera',
            name='cam_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario Camara'),
        ),
        migrations.AddField(
            model_name='historicalcamera',
            name='file',
            field=models.CharField(default='/camera', max_length=200, verbose_name='Extensión'),
        ),
    ]
