# Generated by Django 4.1.7 on 2023-03-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_cam_password_camera_cam_username_camera_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='file',
            field=models.CharField(blank=True, default='/camera', max_length=200, null=True, verbose_name='Extensión'),
        ),
        migrations.AlterField(
            model_name='historicalcamera',
            name='file',
            field=models.CharField(blank=True, default='/camera', max_length=200, null=True, verbose_name='Extensión'),
        ),
    ]
