# Generated by Django 4.1.7 on 2023-06-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_remove_cameraactionlog_target_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraactionlog',
            name='cam_ip',
            field=models.CharField(default='255.255.255.255', max_length=16, verbose_name='ip'),
        ),
    ]
