# Generated by Django 4.1.7 on 2023-06-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_cameraactionlog_cam_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraactionlog',
            name='cam_name',
            field=models.CharField(default='empty_space', max_length=100, verbose_name='Nombre'),
        ),
    ]
